services:
  - type: web
    name: aiblogger-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aiblogger-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: aiblogger-redis
          type: redis
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: OPENAI_API_KEY
        sync: false
      - key: FAL_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
  - type: worker
    name: aiblogger-worker
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m backend.workers.worker_entry
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aiblogger-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: aiblogger-redis
          type: redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: FAL_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
  - type: redis
    name: aiblogger-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction

databases:
  - name: aiblogger-db
    plan: free
    databaseName: aiblogger
    user: aiblogger
    ipAllowList: []
